---
- name: "Freddy Setup"
  hosts: maquinas
  # gather_facts: no
  tasks:
    # - debug:
    #     msg: "{{ ansible_distribution }}"
    # - debug:
    #     msg: "{{ ansible_distribution_version }}"
    - name: Include specific os tasks
      include_tasks:
        file: "os_playbooks/{{ ansible_distribution }}.yml"
    - name: Install packages
      package:
        name: "{{ item }}"
        state: present
        use: "{{ distribution[ansible_distribution].package_manager }}"
      with_items: "{{ distribution[ansible_distribution].packages }}"
      become: yes
    - name: Template qtile session
      template:
        src: ./templates/qtile.desktop
        dest: /usr/share/xsessions/qtile.desktop
        mode: '0775'
      become: yes
    - name: Template config files
      template:
        src: ./templates/.bashrc
        dest: /home/
        mode: '0770'
      become: yes
