---
- name: Add ppa for alacritty
  apt_repository:
    repo: 'ppa:mmstick76/alacritty'
    state: present
  become: yes
- name: Add ppa for vim 8.2
  apt_repository:
    repo: 'ppa:jonathonf/vim'
    state: present
  become: yes
- name: Configuration for spotify
  raw: curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | apt-key add - echo "deb http://repository.spotify.com stable non-free" | tee /etc/apt/sources.list.d/spotify.list
  become: yes
- name: Apt update
  apt:
    update_cache: yes
  become: yes
# - name: Install packages
#   raw: "echo {{packages}}"
#   vars:
#     packages: "{{ distribution[ansible_distribution].packages }}"
